
platform :ios, '8.0'

target '___VARIABLE_productName___' do
	podspec
    # pod 'FFPublicDefineKit', :path=>'../FFCommonService/FFPublicDefineKit'

    target '___VARIABLE_productName___Demo' do
    end

    target :FeiFan do
    end
end
